files:
#  include:
#  - 'inculde/path/to/**/files'
  exclude:
  - '**/*.md'
  - 'node_modules/**/*'
#targets:
#- patterns: ['**/*'] # `patterns` is an array of string, this pattern specify target files for this group
#  rules:
#    <rule-name>:
#      enforce: true # or false
#      <option-key>: <option-value>
      # ...
    # ...
#- patterns: # these rules apply to only .md and .mkd files
  - '**/*.md'
  - '**/*.mkd'
#  rules:
  # ...
# and other patterns and rules ...
